# Generated by Django 4.2.3 on 2023-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_collecthistoryday'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecthistoryday',
            name='fake_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
