# Generated by Django 4.2.3 on 2023-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_collecthistoryday_fake_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='overall',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='gb_favorite',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_avg_position',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_avg_recovery',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_avg_start',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_avg_time',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_best_start',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_best_time',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_brt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_last_recovery',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_last_start',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_last_time',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_recovery',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
