# Generated by Django 4.2.3 on 2023-08-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_races_overall_alter_races_gb_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='gb_favorite',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_avg_position',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_avg_recovery',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_avg_start',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_avg_time',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_best_start',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_best_time',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_brt',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_last_recovery',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_last_start',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_last_time',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='races',
            name='overall_recovery',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
