# Generated by Django 4.2.3 on 2023-09-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_races_gb_favorite_alter_races_overall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='rpr',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
