# Generated by Django 4.2.3 on 2023-09-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_races_rpr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='races',
            old_name='overall_recovery',
            new_name='overall_best_recovery',
        ),
        migrations.AddField(
            model_name='races',
            name='best_recovery',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
