# Generated by Django 4.2.3 on 2023-09-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_overall_recovery_races_overall_best_recovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='track_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
