# Generated by Django 4.2.3 on 2023-09-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_races_track_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='collectOddsDay',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('market_id', models.CharField(max_length=50)),
                ('race_id_betfair', models.CharField(max_length=50)),
                ('market_name', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=150)),
                ('result', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('meeting_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=20)),
                ('event_type_id', models.CharField(max_length=50)),
                ('identify', models.BooleanField(default=False)),
                ('race_greyhound', models.CharField(blank=True, max_length=50)),
                ('race_id', models.CharField(blank=True, max_length=50)),
                ('greyhound_id', models.CharField(blank=True, max_length=50)),
                ('date_added', models.CharField(max_length=50)),
                ('timer_added', models.CharField(max_length=50)),
                ('dog_name', models.CharField(max_length=100)),
                ('selection_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'collectOddsDay',
                'verbose_name_plural': 'collectOddsDay',
            },
        ),
    ]
