# Generated by Django 4.2.3 on 2023-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_collectoddsday'),
    ]

    operations = [
        migrations.CreateModel(
            name='executedOdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.CharField(max_length=50)),
                ('timer_added', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'executedOdd',
                'verbose_name_plural': 'executedOdd',
            },
        ),
        migrations.AlterField(
            model_name='collectoddsday',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
