# Generated by Django 4.2.3 on 2023-09-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_executedodd_alter_collectoddsday_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectoddsday',
            name='dog_name',
        ),
        migrations.RemoveField(
            model_name='collectoddsday',
            name='greyhound_id',
        ),
        migrations.RemoveField(
            model_name='collectoddsday',
            name='race_greyhound',
        ),
        migrations.RemoveField(
            model_name='collectoddsday',
            name='selection_id',
        ),
    ]
