# Generated by Django 4.2.3 on 2023-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_collectoddsday_dog_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hackedProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'hackedProfile',
                'verbose_name_plural': 'hackedProfile',
            },
        ),
    ]
